# Generated by Django 3.1.7 on 2021-03-11 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import se_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authToken', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', se_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Autograde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_grade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Card_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cardgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_grade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='login_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Card_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='front_images')),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('back_thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='front_thumbnails')),
                ('front_thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='back_thumbanils')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='back_images')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('certification_number', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('autographed', models.BooleanField(blank=True, null=True)),
                ('auto_grade', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.autograde')),
                ('card_grade', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.cardgrade')),
                ('category', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.card_category')),
                ('certification', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.certifications')),
                ('status', models.ForeignKey(blank=True, max_length=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user_details',
            name='login_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='se_app.login_types'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
