# Generated by Django 3.1.7 on 2021-03-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autograde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_grade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cardgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_grade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='login_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sports_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('front_thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('back_thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('certification_number', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('auto_grade', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.autograde')),
                ('card_grade', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.cardgrade')),
                ('category', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.sports_list')),
                ('certification', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.certifications')),
                ('status', models.ForeignKey(blank=True, max_length=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.status')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='se_app.details')),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='login_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='se_app.login_types'),
        ),
    ]
