# Generated by Django 3.1.7 on 2021-03-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0002_auto_20210304_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sports_List',
            new_name='Card_Category',
        ),
    ]
