# Generated by Django 3.1.7 on 2021-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0003_auto_20210304_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_details',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
