# Generated by Django 3.1.7 on 2021-03-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0004_card_details_back_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='auth_token',
            new_name='authToken',
        ),
        migrations.AddField(
            model_name='user_details',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(default=123, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='login_type',
            field=models.ForeignKey(default='Kye', on_delete=django.db.models.deletion.CASCADE, to='se_app.login_types'),
        ),
    ]
