# Generated by Django 3.1.7 on 2021-03-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0005_auto_20210312_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autograde',
            old_name='auto_grade',
            new_name='grade_name',
        ),
        migrations.RenameField(
            model_name='card_category',
            old_name='sports',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='cardgrade',
            old_name='card_grade',
            new_name='card_grade_name',
        ),
        migrations.RenameField(
            model_name='certifications',
            old_name='certificates',
            new_name='certificate_name',
        ),
    ]
