# Generated by Django 3.1.7 on 2021-03-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0006_auto_20210312_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='is_staff',
        ),
    ]
