# Generated by Django 3.1.7 on 2021-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0007_remove_user_details_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
