# Generated by Django 3.1.7 on 2021-03-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0009_card_details_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
