# Generated by Django 3.1.7 on 2021-03-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0010_auto_20210315_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_details',
            old_name='flag',
            new_name='is_deleted',
        ),
    ]
