# Generated by Django 3.1.7 on 2021-03-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0011_auto_20210315_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='autographed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
