# Generated by Django 3.1.7 on 2021-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0012_auto_20210316_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='back_thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='back_thumbnails'),
        ),
        migrations.AlterField(
            model_name='card_details',
            name='front_thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='front_thumbanils'),
        ),
    ]
