# Generated by Django 3.1.7 on 2021-03-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_app', '0015_auto_20210318_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
